name: Evil Sarah
favicon: null
layout_spectrum: 0.25371
typography_spectrum: 0.19244
title: "Evil Sarah's Control Board"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#880000'
    - '#46702c'
    - '#c2c100'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
