name: Evil Sarah
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19244
title: "Evil Sarah's Control Board"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c30222'
    - '#000000'
    - '#fefefe'
    - '#00d62c'
    - '#717622'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
